### ISSUE TITLE
`npm run start` fails registering sw, due to using HTTP

### ISSUE THREAD

**Issue by luphoria** [titaniumnetwork-dev/Ultraviolet-App#17]
Issue tracker is **ONLY** used for reporting bugs. New features should be discussed on our Discord server.

## Expected Behavior
SW should register on HTTPS protocol.

## Current Behavior
Ultraviolet starts in http context instead, so SW isn't allowed to start.

## Possible Solution
Use `https` library instead of `http`.

## Steps to Reproduce
- Clone
- Run

**Comment by e9x** [comment]
> Ultraviolet starts in http context instead, so SW isn't allowed to start.

> Use `https` library instead of `http`.


The HTTPS library will not be used due to the amount of complexity it will add to the project.

Here is the implementation options:
- We add a dependency (or write a weird parser) for processing arguments/options and allow specifying a key pair
- We make users create a config.json containing the keys

The first will add complexity to the script's usage and allows for more user error.
```sh
$ PORT=9060 SSL_KEY_PATH=/etc/keys/uv.key SSL_PEM_PATH=/etc/keys/uv.pem npm start
$ PORT=9060 SSL_KEY_PATH=/etc/keys/uv.key SSL_PEM_PATH=/etc/keys/uv.pem pm2 start "npm start" --name uv
```

Of course, the environment can be exported, but users of Ultraviolet-App will likely be deploying to CI where they do not want to write all these lines of environment variables. Some CI may not even allow the user to add the key pair on the system so they will be forced to fork and modify the repository, which adds a lot more possibility for user error.

The second is unpreferable because people may deploy multiple Ultraviolet-Apps, and want to use the same folder. `config.json` scripts have become totally redundant in newer proxy applications in the interest of scaling and simplicity. Any configuration should take place via the CLI/env.

Here is an implementation for setting the default value of the certificates:

- We ship pre-generated SSL certificates such as the ones seen in dozens of earlier proxy repositories
- We use the TLS/crypto library to generate certificates

The first defeats the purpose of SSL and makes the server even more vulnerable to MITM (cannot differentiate between load balance and attacker)

The second adds complexity and makes this no longer a minimal but effective example of Ultraviolet. We would have to write the generated certificates to disk or make the user save them. But this won't work in a deployment environment where no tools can be ran to update the repository on the deployment. Once again, the user will be forced to fork and modify the repository.

NodeJS benefits from the weaker load by having SSL done externally. If a reverse proxy automatically runs NodeJS's traffic through TLS, the NodeJS script shouldn't be expected to do SSL on it's own. It is expected that users use reverse proxies such as NGINX/Caddy/Cloudflare to enable SSL.
Cloudflare is there but opens the possibility for even worse MITM if the origin server isn't using a Cloudflare origin CA.

From my experience with using self-signed certificates served via an IP address, I found that ServiceWorkers over an insecure (yet HTTPS:) domain were very quirky and threw an error every other request.

The technicality of the users comes into question too:
If one is willing to get a signed certificate in order to overcome the quirks of self-signing, shouldn't they be qualified enough to use a reverse proxy?

Most deployment services offer SSL anyway, as they're just updating their reverse proxy config automatically. This would be useless to the average user.

**Comment by luphoria** [comment]
You don't need an upstream CA to trust certificates. I just imported my dev key to my machine

**Comment by e9x** [comment]
I am able to run Ultraviolet on HTTP over localhost and 127.0.0.1 on Chrome & Firefox without any issues.
Due to my inability to reproduce this error and this being useless for the reasons described above, I will be closing this.
